pipeline {
    agent none

    stages {
        stage('Unit Tests Backend') {
            agent {
                docker {
                    image 'golang:1.21'
                    args '-e GOCACHE=/tmp/go-build -e GOMODCACHE=/tmp/go-mod'
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                }
            }
        }
    }
}
